version: '3.8'

services:
  fastapi-server:
    build: .

    container_name: fastapi-server

    ports:
      - "8086:8086"

    environment:
      - PYTHONUNBUFFERED=1

    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 5