[project]
name = "server-prova"
version = "0.1.0"
description = "FastAPI + ADK Web server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.136.1",
    "uvicorn>=0.46.0",
    "google-adk>=1.33.0",
    "litellm>=1.0.0",
    "sloppy-xml>=0.3.1",
    "ag-ui-adk>=0.6.0",
]
